apiVersion: apps/v1
kind: Deployment
metadata:
  name: agile-toggle-mkdocs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agile-toggle-mkdocs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: agile-toggle-mkdocs
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: agile-toggle-mkdocs
        image: agiletoggle.azurecr.io/agile-toggle-mkdocs:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 150m
          limits:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: agile-toggle-mkdocs
spec:
  ports:
  - port: 80
  selector:
    app: agile-toggle-mkdocs


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: agile-toggle-mkdocs
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: docs.feature-flags.co
    http:
      paths:
      - path: /
        backend:
          serviceName: agile-toggle-mkdocs
          servicePort: 80