site_name: " "
nav:
  - 简介: index.md
  - 快速入门:
    - quickstart/create-flag.md
    - 1. 创建开关: quickstart/create-flag.md
    - 2. 添加自定义属性: quickstart/add-attribute.md
    - 3. 集成开关到产品中: quickstart/sdk-integration.md
    - 4. 细粒度发布、回退功能: quickstart/release-rollback.md
    - 5. 数据收集: quickstart/send-event.md
    - 6. 数据实验: quickstart/abtest.md
  - Feature团队协作流: 
    - featureworkflow/index.md
    - 合并请求: featureworkflow/approval.md
    # - 计划变更: quickstart/featureworkflow/schedule.md
    - 事件触发: featureworkflow/trigger.md
    # - Webhook: quickstart/featureworkflow/webhook.md
    # - 操作日志: quickstart/featureworkflow/auditlog.md
    - 数据同步: 
      - feature数据同步: ffsync/envdatasync.md
      - 本地版与SaaS数据同步: ffsync/saaslocaldatasync.md
    - 多租户与项目管理: account-setting.md
  # - 从数据实验到业务增长: 
  #   - A/B/n测试: experiments/abntest.md
    # - 导出数据至三方工具: quickstart/ffsync/exportdata.md
  - 低代码集成(SDK):
    - SDK: opensource/sdk.md
    - Web API: opensource/webapi.md
    - 辅助工具: 
      - 代码快速定位: codetool/codereference.md
  - 网站链接: 
    - 官方网站: https://www.feature-flags.co
    - Portal: https://portal.feature-flags.co
  
  - 技术披露: 
    - Flag判断条件流程图: quickstart/flag-check-variation-flow.md
    - Rollout分配算法: quickstart/rollout-algo.md

  # - 特征管理指南:
  #   - 特征管理的权威指南: feature-management/guide.md
  #   - "构建 Build (支柱一)": feature-management/build.md
  #   - "运营 Operate (支柱二)": feature-management/operate.md
  #   - "学习 Learn (支柱三)": feature-management/learn.md
  #   - "赋能 Empower (支柱三)": feature-management/empower.md
  #   - 敏捷开关的视野: feature-management/vision.md
repo_url: https://github.com/feature-flags-co/feature-flags-co
theme:
  name: material
  language: zh 
  logo: img/ff_logo+text_white.png
  favicon: img/favicon.ico
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.indexes
  palette:
    - scheme: default
      primary: "#4CB287"
      accent: "#4CB287"
    - scheme: slate
      primary: "#4CB287"
      accent: "#4CB287"
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
  - stylesheets/simpleLightbox.min.css
extra_javascript:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - javascripts/simpleLightbox.min.js
  - javascripts/extensions.js
extra:
  # generator: false
  search:
    language: 'en, zh'
  social:
    # - icon: fontawesome/brands/github
    #   link: https://github.com/feature-flags-co/feature-flags-co
    #   name: 'feature-flags-co'
copyright: Copyright &copy; 天博助力 - 敏捷开关 feature-flags.co 版权所有 京ICP备2021017279号
plugins:
  - ffc-mkdocs-video
  - search
  - section-index
markdown_extensions:
  - pymdownx.tabbed
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list
